#!/usr/bin/env bash
# Removes build artifacts that are committed to git even though .gitignore
# already lists them. They were added before the ignore rules existed, and
# .gitignore has no effect on files that are already tracked.
#
# This only changes the git index — your working tree is left alone.
# Review with `git status` and commit when you are happy.
set -euo pipefail

cd "$(dirname "$0")/.."

git rm -r --cached --quiet src/piper.egg-info
git rm    --cached --quiet .pipeline/detection.json
git rm    --cached --quiet test_report.json

echo "Untracked:"
echo "  src/piper.egg-info/     (regenerated by every editable install)"
echo "  .pipeline/detection.json (piper's own output)"
echo "  test_report.json         (stray scan artifact at the repo root)"
echo
echo "Review with 'git status', then commit."
